
# declaring the types of testing which medic can prescribe (it is used while creating an instance of a referral)
TEST_TYPE = (
            ('ANALITYKA OGÓLNA - Badanie ogólne moczu','ANALITYKA OGÓLNA - Badanie ogólne moczu'),
            ('ANALITYKA OGÓLNA - Kał badanie ogólne','ANALITYKA OGÓLNA - Kał badanie ogólne'),
            ('HEMATOLOGIA - Morfologia krwi', 'HEMATOLOGIA - Morfologia krwi'),
            ('HEMATOLOGIA - OB', 'HEMATOLOGIA - OB'),
            ('KOAGULOGIA - Fibrogen', 'KOAGULOGIA - Fibrogen'),
            ('KOAGULOGIA - TT', 'KOAGULOGIA - TT'),
            ('CHEMIA KLINICZNA - Glukoza', 'CHEMIA KLINICZNA - Glukoza'),
            ('CHEMIA KLINICZNA - Sód', 'CHEMIA KLINICZNA - Sód'),
            ('CHEMIA KLINICZNA - Potas', 'CHEMIA KLINICZNA - Potas'),
            ('CHEMIA KLINICZNA - Wapń', 'CHEMIA KLINICZNA - Wapń'),
            ('CHEMIA KLINICZNA - Kreatynina', 'CHEMIA KLINICZNA - Kreatynina'),
            ('CHEMIA KLINICZNA - Billirubina całkowita','CHEMIA KLINICZNA - Billirubina całkowita'),
            ('CHEMIA KLINICZNA - ALP', 'CHEMIA KLINICZNA - ALP'),
            ('CHEMIA KLINICZNA - Amylaza', 'CHEMIA KLINICZNA - Amylaza'),
            ('CHEMIA KLINICZNA - Lipaza', 'CHEMIA KLINICZNA - Lipaza'),
            ('CHEMIA KLINICZNA - Profil lipidowy', 'CHEMIA KLINICZNA - Profil lipidowy'),
            ('CHEMIA KLINICZNA - Triglierydy', 'CHEMIA KLINICZNA - Triglierydy'),
            ('CHEMIA KLINICZNA - Żelazo', 'CHEMIA KLINICZNA - Żelazo'),
            ('CHEMIA KLINICZNA - Ferrytyna', 'CHEMIA KLINICZNA - Ferrytyna'),
            ('CHEMIA KLINICZNA - Hemocysteina', 'CHEMIA KLINICZNA - Hemocysteina'),
            ('CHEMIA KLINICZNA - Albumina', 'CHEMIA KLINICZNA - Albumina'),
            ('CHEMIA KLINICZNA - Białko całkowite','CHEMIA KLINICZNA - Białko całkowite'),
            ('MARKERY KARDIOLOGICZNE - CKMB aktywność','MARKERY KARDIOLOGICZNE - CKMB aktywność'),
            ('MARKERY NOWOTWOROWE - AFP', 'MARKERY NOWOTWOROWE - AFP'),
            ('MARKERY NOWOTWOROWE - PSA całkowity','MARKERY NOWOTWOROWE - PSA całkowity'),
            ('ENDOKRYNOLOGIA - Progesteron', 'ENDOKRYNOLOGIA - Progesteron'),
            ('ENDOKRYNOLOGIA - Kortyzol', 'ENDOKRYNOLOGIA - Kortyzol'),
            ('ENDOKRYNOLOGIA - Insulina', 'ENDOKRYNOLOGIA - Insulina'),
            ('ENDOKRYNOLOGIA - Prolaktyna', 'ENDOKRYNOLOGIA - Prolaktyna'),
            ('DIAGNOSTYKA INFEKCJI - Anty HCV', 'DIAGNOSTYKA INFEKCJI - Anty HCV'),
            ('DIAGNOSTYKA INFEKCJI - Odra IgG', 'DIAGNOSTYKA INFEKCJI - Odra IgG'),
            ('DIAGNOSTYKA INFEKCJI - Ospa IgG', 'DIAGNOSTYKA INFEKCJI - Ospa IgG'),
            ('DIAGNOSTYKA INFEKCJI - Glista ludzka IgG','DIAGNOSTYKA INFEKCJI - Glista ludzka IgG'),
            ('AUTOIMMUNOLOGIA - ANA ELISA', 'AUTOIMMUNOLOGIA - ANA ELISA'),
            ('AUTOIMMUNOLOGIA - dsDNA', 'AUTOIMMUNOLOGIA - dsDNA'),
            ('ALERGOLOGIA - Zestaw pokarmowy 20', 'ALERGOLOGIA - Zestaw pokarmowy 20'),
            ('ALERGOLOGIA - Zestaw wziewny 20', 'ALERGOLOGIA - Zestaw wziewny 20'),
            ('BADANIE MOCZU - Białko w moczu', 'BADANIE MOCZU - Białko w moczu'),
            ('BADANIE MOCZU - Kreatynina w moczu', 'BADANIE MOCZU - Kreatynina w moczu')    
    )


